# Generated by Django 6.0.5 on 2026-05-16 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="authors/avatars/%Y/%m/"),
                ),
                ("website", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                ("github_handle", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "author profile",
                "db_table": "author_profiles",
            },
        ),
    ]
