# Generated by Django 6.0.5 on 2026-05-16 12:36

import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("excerpt", models.TextField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("body_html", models.TextField(blank=True, editable=False)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="posts/covers/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("reading_time", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("og_title", models.CharField(blank=True, max_length=300)),
                ("og_description", models.TextField(blank=True, max_length=160)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="posts/og/%Y/%m/")),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="PostAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("total_shares", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "post_analytics",
            },
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("love", "Love"),
                            ("insightful", "Insightful"),
                            ("bookmark", "Bookmark"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_reactions",
            },
        ),
    ]
