# Generated by Django 6.0.5 on 2026-05-16 12:36

import django.contrib.postgres.indexes
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postanalytics",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status", "published_at"], name="posts_status_862f99_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["author", "status"], name="posts_author__d284fa_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-published_at", "status"], name="posts_publish_65c598_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="post_search_vector_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(fields=["post", "reaction"], name="post_reacti_post_id_adfe5a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="postreaction",
            unique_together={("post", "user", "reaction")},
        ),
    ]
